model:
  base_model: "google/gemma-3-4b-it"
  lora_repo: "Sentinel-AI/neurips_grpo_model"
  device: "cuda:0" # Add empty gpu after running nvidia smi
  max_new_tokens: 96
  cache_dir: "/ewsc/lluebber/sentinel-checkpoints/GRPO-Neurips/"

data:
  train_test_data_folder: "/ewsc/lluebber/projects/snow/data/test_train_splits_llm_v2/"
  pathogen: "all-viral-malaria"
  data_path: "/ewsc/lluebber/projects/snow/data/SentinelNigeria_DATA_2025-10-17_1300_llm_clean.csv"
  col_meta_path: "/ewsc/lluebber/projects/snow/data_small/pathogen_metadata_v2.xlsx"
  sheet_name: "columns_metadata_v2"
  data_dictionary_path: "/ewsc/lluebber/projects/snow/data/SentinelNigeria_DataDictionary_2025-05-02.csv"
  batch_size_train: 16
  batch_size_eval: 40
  num_workers: 0

eval:
  eval_name: "benchmark_v2_v2"
  device: "cuda:0"