model:
  base_model: "google/medgemma-1.5-4b-it"
  lora_repo: "Sentinel-AI/sft_new_data"
  device: "cuda:0"
  max_new_tokens: 96
  cache_dir: "/ewsc/yektefai/sentinel-checkpoints/SFT-NewData/"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05

data:
  train_test_data_folder: "/ewsc/lluebber/projects/snow/data/test_train_splits_llm_v2/"
  pathogen: "all-viral-malaria"
  data_path: "/ewsc/lluebber/projects/snow/data/SentinelNigeria_DATA_2025-10-17_1300_llm_clean.csv"
  col_meta_path: "/ewsc/lluebber/projects/snow/data_small/pathogen_metadata_v2.xlsx"
  sheet_name: "columns_metadata_v2"
  data_dictionary_path: "/ewsc/lluebber/projects/snow/data/SentinelNigeria_DataDictionary_2025-05-02.csv"
  new_data: true
  no_malaria: true
  batch_size_train: 1
  batch_size_eval: 4
  num_workers: 0

eval:
  eval_name: "benchmark_new_data"
  device: "cuda:0"
